<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>TopoTIN.Core</RootNamespace>
    <AssemblyName>TopoTIN.Core</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

<ItemGroup>
    <ProjectReference Include="..\TriangleNet\TriangleNet.csproj" />
  </ItemGroup>
</Project>
