# Regenerates docs/file-index.md: a path -> one-line-summary map of the MoleHill source, so an AI
# agent (or human) can grep one file to find where things live. The summary is the file's first
# header comment (// or /// <summary>). Run: pwsh ./generate-file-index.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$projects = @('src/MoleHill.Core', 'src/MoleHill.Interop', 'src/MoleHill.Rhino', 'src/MoleHill.Grasshopper', 'src/MoleHill.Shared')

function Get-Summary([string]$path) {
    # -Encoding UTF8 is required: Windows PowerShell 5.1 otherwise decodes these UTF-8 sources as
    # ANSI, turning arrows and em-dashes in doc comments into mojibake in the generated index.
    foreach ($line in Get-Content -LiteralPath $path -TotalCount 40 -Encoding UTF8) {
        $t = $line.Trim()
        if ($t -like '/// <summary>*') {
            $s = $t.Replace('/// <summary>', '').Replace('</summary>', '').Trim()
            if ($s) { return $s }
            continue
        }
        if ($t -like '///*') {
            $s = $t.TrimStart('/').Trim()
            if ($s -and $s -notlike '<*') { return $s }
            continue
        }
        if ($t -like '//*' -and $t -notlike '//-*') {
            return $t.TrimStart('/').Trim()
        }
    }
    return ''
}

# When a file has no header comment, say what can be read off it rather than leaving the entry blank:
# the command a Rhino command class registers, or the type a partial-class file belongs to.
function Get-Fallback([string]$path) {
    $text = [System.IO.File]::ReadAllText($path)
    $command = [regex]::Match($text, 'EnglishName\s*=>\s*"([^"]+)"')
    if ($command.Success) { return "Rhino command ``$($command.Groups[1].Value)``." }

    $name = [System.IO.Path]::GetFileNameWithoutExtension($path)
    $dot = $name.IndexOf('.')
    if ($dot -gt 0) {
        $type = $name.Substring(0, $dot)
        $part = $name.Substring($dot + 1)
        if ($text -match "partial\s+(class|struct|record)\s+$([regex]::Escape($type))\b") {
            return "``$type`` partial: $part."
        }
    }
    return ''
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# File index')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Auto-generated by `generate-file-index.ps1`. Path -> first header summary; without one, the command a file registers or the partial type it belongs to. Do not edit by hand.')
[void]$sb.AppendLine()

foreach ($project in $projects) {
    $full = Join-Path $root $project
    if (-not (Test-Path $full)) { continue }
    $files = Get-ChildItem -Path $full -Recurse -Filter *.cs |
        Where-Object { $_.FullName -notmatch '[\\/](obj|bin|artifacts)[\\/]' } |
        Sort-Object FullName
    if (-not $files) { continue }
    [void]$sb.AppendLine("## $project")
    [void]$sb.AppendLine()
    foreach ($file in $files) {
        $rel = $file.FullName.Substring($root.Length + 1).Replace('\', '/')
        $summary = Get-Summary $file.FullName
        if (-not $summary) { $summary = Get-Fallback $file.FullName }
        if ($summary) {
            [void]$sb.AppendLine("- ``$rel`` - $summary")
        }
        else {
            [void]$sb.AppendLine("- ``$rel`` -")
        }
    }
    [void]$sb.AppendLine()
}

$outPath = Join-Path $root 'docs/file-index.md'
[System.IO.File]::WriteAllText($outPath, $sb.ToString())
Write-Output "Wrote $outPath ($(($sb.ToString() -split "`n").Count) lines)"
