<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>C:\Program Files\Rhino 8\System\netcore\RhinoCommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Rhino.UI">
      <HintPath>C:\Program Files\Rhino 8\System\netcore\Rhino.UI.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
