<Project>
  <!-- Use a unique name to avoid being overridden by the NuGet package -->
  <Target Name="MergeAssemblies" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)$(TargetName)$(TargetExt)" />
      <InputAssemblies Include="$(OutputPath)MoleHill.Core.dll" />
    </ItemGroup>

    <ILRepack
      Parallel="true"
      DebugInfo="true"
      AllowDuplicateResources="false"
      InputAssemblies="@(InputAssemblies)"
      TargetKind="SameAsPrimaryAssembly"
      OutputFile="$(OutputPath)$(TargetName)$(TargetExt)" />

    <Delete Files="$(OutputPath)MoleHill.Core.dll;$(OutputPath)MoleHill.Core.pdb" ContinueOnError="true" />
  </Target>
</Project>
